runtime: custom
env: flex
entrypoint: gunicorn app:app --log-file=- --pythonpath src,src/chessid -b :$PORT

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

health_check:
  enable_health_check: False

skip_files:
- data/
- notebooks/
- ^(.*/)?.*\.tar$
- ^(.*/)?.*\.jpg$